title: "Aditya J Thamarasseril"
description: "Aspiring Mechanical & Robotics Engineer | CFD | IoT | AP Scholar with Distinction"
theme: minima

url: "https://tjaditya.com"
github_username: tjaditya

header_pages:
  - about.md
  - projects.md
  - photography.md
